### ISSUE TITLE
The last opened website is wrongly displayed instead of the previously navigated website inside the sidebar, after it was switched or reopened

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#106]
[Affected versions]:
- Firefox 59.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have the Tab Split sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to any website.
2. Click the tab from the "Current Tabs" section and click a hyperlinked element, inside the sidebar.
3. Change the sidebar to a different one.
4. Switch back to "Tab Split" and observe the displayed content.

[Expected result]:
- The previously navigated content is displayed.

[Actual result]:
- The content of the opened tab from "Current Tabs" section is displayed.

[Notes]:
- Here is a screen recording with this issue:
![previously navigated content](https://user-images.githubusercontent.com/31244235/37976426-2e21bca2-31ea-11e8-9971-2e5985be4aba.gif)

**Comment by ianb** [comment]
Unfortunately we can't track updates to the iframe, so we don't see these URL changes and can't restore the URL. If #98 worked like we *hoped* it would work, then it would be harder to notice this constraint.

**Comment by ianb** [comment]
While the restore behavior is not entirely consistent now (and is partially but not completely shared among windows), I believe this particular issue is OK now that we've removed the iframe.
