### ISSUE TITLE
Add webextension api experiment support to web-ext

### ISSUE THREAD

**Issue by fzzzy** [mozilla/side-view#108]
Now that we depend on a webextension api experiment, we need to fix web-ext so that it adds the experiment to the xpi. I believe there is an existing bug about this in the web-ext repo, but it hasn't been fixed yet.

**Comment by ExE-Boss** [comment]
That’s issue mozilla/web-ext#741.

**Comment by ianb** [comment]
I think this is all working (and have noted this on the web-ext bug as well)
