### ISSUE TITLE
Links are wrongly accessed in the sidebar, on Windows and Mac OSes

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#114]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.2.0 installed.
- Have the Side View sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to any website.
2. Click the tab from the "Current Tabs" section.
3. Click a hyperlinked element, inside the sidebar and observe the behavior.

[Expected result]:
- The content is loaded in the opened tab.

[Actual result]:
- The content is loaded in the sidebar.

[Notes]:
- This issue is not reproducible on Linux OSes.
- Here is a screen recording with this issue:
![navigate inside the sidebar](https://user-images.githubusercontent.com/31244235/38098585-23829486-3381-11e8-9998-bac97e316166.gif)

**Comment by johngruen** [comment]
AFAICT Same origin opens in sidebar

**Comment by johngruen** [comment]
Wontfix
