### ISSUE TITLE
Links sent to the sidebar with the "Open link in sidebar" context menu option don't appear in the "Recent Tabs" section

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#121]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 2 0.2.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.2.0 installed.
- Have the Side View sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to a website.
2. Right click on a hyperlinked element and select the "Open link in sidebar" context menu option.
3. Click the sidebar's "Home" button.
4. Observe the "Recent Tabs" section.

[Expected result]:
- The previously loaded website is displayed.

[Actual result]:
- The previously loaded website is not displayed.

[Notes]:
- This issue is not reproducible if you use the "Open in sidebar" option from the tab in the tab strip.
- Here is a screen recording with this issue:
![open link in sidebar](https://user-images.githubusercontent.com/31244235/38138600-65d43944-3434-11e8-9440-d4ad86b62940.gif)

**Comment by ianb** [comment]
We can't get the title of links, so we've decided just to leave them out of Recent Tabs
