### ISSUE TITLE
The sidebar wrongly remains blank when certain websites are sent to it

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#122]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 2 0.2.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.2.0 installed.
- Have the Side View sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to https://edition.cnn.com/.
2. Click the "Open current tab in sidebar" toolbar button and observe the behavior.

[Expected result]:
- The website is loaded in the sidebar.

[Actual result]:
- The sidebar remains blank.

[Notes]:
- This issue is also reproducible for https://www.instagram.com/.- This issue is also reproducible for https://www.instagram.com/. So far these are the only two websites that I've found to do this, but there could be more
- Here is a screen recording with this issue:
![blank sidebar](https://user-images.githubusercontent.com/31244235/38141318-2c1ef494-3440-11e8-8c4e-0de9ab23a2e9.gif)

**Comment by johngruen** [comment]
This is resolved
<img width="1727" alt="screen shot 2018-04-16 at 6 44 17 pm" src="https://user-images.githubusercontent.com/3323249/38838876-37ff1c80-41a6-11e8-9d5d-994601d3466c.png">
