### ISSUE TITLE
"LOADING..." state is displayed in the child tab after reopening the "Side view" sidebar with an empty content

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/side-view#123]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 2 0.2.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.2.0 installed.
- Have the Side View sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "x" button from the top right of the sidebar.
3. Click the "Side View" toolbar button and observe the content of the sidebar.

[Expected result]:
- The sidebar is displayed.

[Actual result]:
- The sidebar displays the "LOADING..." text, "Home" and "Refresh" buttons and "Request desktop site" checkbox.

[Notes]:
- This issue originally started when I had ~5 opened tabs. After following the same steps above, the sidebar displayed a blank content. I'll investigate this more and report if it's still actual.
- Here is a screen recording of this issue:

![close side view](https://user-images.githubusercontent.com/26000308/38141478-0503c668-3441-11e8-9084-ea27af872825.gif)

**Comment by johngruen** [comment]
We need to check for non http(s) pages and do the right thing

**Comment by johngruen** [comment]
ie open the sv homepage
