### ISSUE TITLE
[Intermittent] If the sidebar is closed, it wrongly becomes blank or the sidebar's Homepage UI is wrongly displayed after sending a website to it

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#125]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 2 0.2.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.2.0 installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to a website.
2. Close the sidebar and right click the open tab.
3. Select the "Open in sidebar" context menu option observe the behavior.
4. Repeat step 2 and 3 at least 10 times and observe the behavior each time.

[Expected result]:
Step 3 & 4 - The website is loaded in the sidebar.

[Actual result]:
Step 3 & 4: - The behavior is inconsistent: sometimes the sidebar becomes blank, the sidebar's Homepage UI is displayed or the website is loaded.

[Notes]:
- This issue is also reproducible with "Open link in sidebar" context menu option and with the "Open current tab in sidebar" toolbar button, after 4-6 clicks on these options.
- This issue is easier to reproduce on Linux OSes.
- Here is a screen recording with this issue:
![side view - intermittent](https://user-images.githubusercontent.com/31244235/38191376-232beab2-3671-11e8-9cb2-7471c1c2ec2c.gif)

**Comment by johngruen** [comment]
I think we can close this...I tried this a bunch and couldn't repro
Closest i got was with https://app.surveygizmo.com/ which is an EXTRMELY SLOW website, but even that popped in after a few seconds

**Comment by Softvision-CristinaBadescu** [comment]
Yes, we can close it. I've also retested this issue with several websites and I was not able to reproduce it using the latest Side View 0.3.2 (custom built on 2018-04-18), on latest Nightly build 61.0a1 (Build ID: 20180417225505), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.
