### ISSUE TITLE
If the sidebar is closed, clicking the Side View toolbar button in other windows wrongly shows the the sidebar's Homepage UI

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#126]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 2 0.2.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.2.0 installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and open a new window.
2. Close the sidebar and navigate to a website.
3. Click the "Open current tab in sidebar" toolbar button and observe the behavior.
[Expected result]:
- The website is loaded in the sidebar.

[Actual result]:
- The sidebar's homepage UI is displayed.

[Notes]:
- This issue is also reproducible with the "Open in sidebar" context menu option from the tab in the tab strip, or with the "Open link in sidebar" context menu option.
- The website is loaded in the sidebar only after you click the toolbar button again.
- Here is a screen recording with this issue:
![side view - other windows](https://user-images.githubusercontent.com/31244235/38191629-2c048378-3672-11e8-8692-c81759c16c2f.gif)

**Comment by ianb** [comment]
This particular flow no longer exists, so the bug is no longer applicable.
