### ISSUE TITLE
The sliding animation is wrongly reset for a brief moment if the "Tab" key is quickly pressed after the sidebar's "Home" button

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#127]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 2 0.2.0

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.2.0 installed.
- Have one tab open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the tab from the "Open Tabs" section.
3. Click the sidebar's "Home" button and quickly press the "Tab" key.
4. Observe the behavior while performing step 3.

[Expected result]:
- The sliding animation is smooth.

[Actual result]:
- The sliding animation resets for a brief moment.

[Notes]:
- Here is a screen recording with this issue:
![side view - reset animation](https://user-images.githubusercontent.com/31244235/38201613-931aa158-36a1-11e8-8dfb-049d02de6779.gif)

**Comment by ianb** [comment]
This seems... fine for an experiment.
