### ISSUE TITLE
There is no sliding animation for websites opened from the toolbar button or the context menu options when the sidebar's "Home" button is clicked

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#128]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.2.0 installed.
- Have one tab open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Open current tab in sidebar" toolbar button.
3. Click the sidebar's "Home" button and observe the behavior.

[Expected result]:
- The current tab from the sidebar slides to the right revealing the sidebar's Homepage UI.

[Actual result]:
- The sliding animation is not performed.

[Notes]:
- This issue is also reproducible with the "Open in sidebar" context menu option from the tab in the tab strip and with the "Open link in sidebar" context menu.
- Also, on Windows and Linux OSes, if you rapidly press "Tab" key after you click the sidebar's "Home" button, the previous loaded website is wrongly displayed for a second. On Mac OSes, only a shadow appears in the sidebar's margin. This behavior could be a dupe of #127 .
- Here is a screen recording with this issue:
![side view - no slide animation](https://user-images.githubusercontent.com/31244235/38201331-9b5eae8c-36a0-11e8-9fdc-f0a1123b9989.gif)

**Comment by ianb** [comment]
We no longer have any animations, so this no longer applies.
