### ISSUE TITLE
No tooltip is displayed when hovering the domain name from the Side View child page

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/side-view#139]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.2.0 installed.
- Have one tab open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the tab from the "Current Tabs" section.
3. Move the mouse over the domain name from the Side View header and observe the behavior.

[Expected result]:
- The domain name is displayed as a tooltip.

[Actual result]:
- No tooltip is displayed.

[Notes]:
- Here is a screen recording with this issue:
![sideview_title](https://user-images.githubusercontent.com/20083658/38312679-0a06062e-382b-11e8-8053-b91769ac6af8.gif)

**Comment by ianb** [comment]
The domain is gone so this is no longer applicable.
