### ISSUE TITLE
Odd behavior when trying to focus sidebar elements with the "Tab" key

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#142]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.2.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.2.0 installed.
- Have 1 tab displayed in the "Recent Tabs" section.
- Have 1 tab open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click inside the empty space from the sidebar.
3. Press the "Tab" key once.

[Expected result]:
- The tab from the "Recent Tabs section is focused.

[Actual result]:
- The "Feedback" button is focused. 
or 
- The tab from the "Current Tabs" section is focused.
 or
 - The tab form "The Recent Split Tabs is focused.

[Notes]:
- It looks like every time I refocus the sidebar and press Tab, a different element is focused first.
- Here is a screen recording with this issue:
![sideview - odd behavior](https://user-images.githubusercontent.com/31244235/38364514-b4bff2bc-38e1-11e8-8d4b-785fd48fccf6.gif)

**Comment by ianb** [comment]
I don't think this applies any longer since we've moved to a popup. Tab doesn't work so well, but in a different way.
