### ISSUE TITLE
A new "Sidebar" tab is wrongly opened if you click the "Feedback" button, on Linux OSes

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#143]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.2.0

[Affected Platforms]:
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.2.0 installed.
- Have one tab open.
- Have the "Side View" sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Feedback" button and observe the behavior.

[Expected result]:
- A feedback survey is opened in a new tab.

[Actual result]:
- A new "Sidebar" tab is opened and the tab from the "Current Tabs" section disappears.

[Notes]:
- We don't have yet a feedback survey link.
- On Windows and Mac OSes the sidebar's Homepage UI flickers.
- Here is a screen recording with this issue: https://goo.gl/qBWmKd

**Comment by ianb** [comment]
I think with the popup that this is fixed (assigning back to @Softvision-CristinaBadescu to reconfirm, since I don't have a Linux machine to test on).

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Side View v0.3.2, on latest Nightly build 61.0a1 (2018-04-23) on Arch Linux 4.12 and Ubuntu 14.04 x64. When the "Give Feedback" button is clicked from the pop up, a new tab with the survey is opened.

However, clicking the "Give Feedback" hyperlinked text from the "Welcome" screen, opens the link in the focused tab. I've logged the issue here #199.
