### ISSUE TITLE
The previously opened website from the "Current Tabs" section is wrongly loaded in the sidebar, if another link is sent to it and the toolbar button is clicked

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#152]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.3.2.

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.
- Have the Side View sidebar open.
- Have one tab open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Open Side View" toolbar button and select the website from the "Current Tabs" section.
3. Open a new tab and navigate to a different website.
4. Right click the tab from the tab strip and select the "Open in sidebar" option.
5. Click the "Open Side View" toolbar button and observe the behavior.

[Expected result]:
- The Side View doorhanger is displayed.

[Actual result]:
- The previous opened website is loaded in the sidebar.

[Notes]:
- This issue is also reproducible with the "Open link in sidebar" context menu option.
- Here is a screen recording with this issue: 
![side view - previously opened website](https://user-images.githubusercontent.com/31244235/38687535-92c3ac8c-3e7f-11e8-831e-53aa886927b1.gif)

**Comment by johngruen** [comment]
Can't repro 🤷‍♂️

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Side View v0.3.2, on latest Nightly build 61.0a1 (2018-04-18), on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12.
