### ISSUE TITLE
The sidebar does not open if you click any website from the Side View panel

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#153]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.3.2.

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.
- Have the Side View sidebar closed.
- Have one tab open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Open Side View" toolbar button.
3. Select the website from the "Current Tabs" section and observe the behavior.

[Expected result]:
- The Side View sidebar is opened and the website is loaded in it.

[Actual result]:
- The sidebar does not open.

[Notes]:
- This issue is also reproducible with the website from the "Recent Tabs" section.
- Here is a screen recording with this issue: 
![side view - closed sidebar](https://user-images.githubusercontent.com/31244235/38688923-f1d041a6-3e82-11e8-934e-bf74e4add606.gif)

**Comment by ianb** [comment]
Note it *does* work when you use the context menu. Maybe the popup should ask the background page to open the sidebar, to keep the logic the same.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using latest Side View v0.3.2, on latest Nightly build 61.0a1 (2018-04-13), on Windows 10 x64, Mac 10.13.4 and Arch Linux 4.12. If the sidebar is closed, it opens when you click any website from the Side View panel.
