### ISSUE TITLE
"Request desktop site" ui needs to be hooked up

### ISSUE THREAD

**Issue by fzzzy** [mozilla/side-view#158]
When we switched to the new 0.3 panel, we lost the ability to request the desktop site.

**Comment by fzzzy** [comment]
Now there's ui for it, but it's not hooked up.

**Comment by johngruen** [comment]
Here's how it should work:

1. if the user is just looking at the panel and not viewing a site, there should be a `toggle-disabled` class applied to the parent `panel-footer` element
2. if the user is looking at a site, the string in `mobile-toggle` should read either *Ask for Desktop Site* or *Ask for Mobile Site* depending on current sites.
3. Previously visited sidebar sites should remember whether desktop or mobile.
4. Sites visited in private browsing should no be remembered and and default to mobile
