### ISSUE TITLE
The "Ask for Desktop Site" and "Give Feedback" buttons are not visible in the panel when more than 20 websites are open

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#174]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.3.2.

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.
- Have no websites in the "Recent Tabs" section.
- Have 20 websites open in different tabs.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Open a new tab and navigate to any website.
3. Click the "Open Side View" toolbar button.
4. Scroll down and observe the bottom of the panel.

[Expected result]:
- "Ask for Desktop Site" and "Give Feedback" buttons are displayed.

[Actual result]:
- No buttons are displayed.

[Notes]:
- This issue is not reproducible if you have under 19 open tabs.
- If you have 20 tabs open, the buttons are partially visible.
- If you have more than 20 tabs open, the buttons are no longer displayed.
- On Windows 10 x64, when you scroll you can see a part of "Recent Tabs" text.
- Here is a screen recording with this issue:
![side view - buttons not visible](https://user-images.githubusercontent.com/31244235/38808505-255ef568-4189-11e8-86af-331cddbf2a00.gif)

**Comment by johngruen** [comment]
Closing in favor of #151

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Side View v0.3.2, on latest Nightly build 61.0a1 (2018-04-18), on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12.
