### ISSUE TITLE
The Side View page action option/button does not open the sidebar if it was previously closed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/side-view#175]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.3.2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Close the Side View sidebar and navigate to a website.
3. Click the "Open Side View" page action button and observe the behavior.

[Expected result]:
- The website is loaded in the sidebar.

[Actual result]:
- Nothing happens.

[Notes]:
- The issue is also reproducible if a different sidebar is opened. The option/button does not do anything if the Bookmarks sidebar is opened.
- The Page action option/button work as expected if the Side View sidebar is opened.
- The issue is not reproducible if the Toolbar button or the context menu option are clicked.
- Here is a screen recording with this issue:
![side view page action button does not open the sidebar if it is closed](https://user-images.githubusercontent.com/18304511/38810363-3781f870-418f-11e8-874d-d1aaabd1096a.gif)

**Comment by johngruen** [comment]
Let's just back this out for launch...not sure how much it adds

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Side View v0.3.2, on latest Nightly build 61.0a1 (2018-04-23), on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12.
