### ISSUE TITLE
Thin gray line wrongly appears if you hover the area between last website and the panel's buttons, on Windows

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#178]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.3.2.

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.
- Have 1 website open in different 8 tabs.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Open Side View" toolbar button and hover the last website.
3. Hover the white space between the last website and the buttons from the bottom of the sidebar.
4. Observe the behavior.

[Expected result]:
- The area remains white.

[Actual result]:
- A thin gray line appears.

[Notes]:
- This issue is also reproducible if you have websites in the "Recent Tabs" section.
- This issue is not reproducible if you first hover the buttons and afterwards the white area.
- Here is a screen recording with this issue:
![side view - gray line](https://user-images.githubusercontent.com/31244235/38816558-09a0cc96-419f-11e8-9deb-bf5e9a6d594b.gif)

**Comment by johngruen** [comment]
@Softvision-CristinaBadescu I can repro this on a Win 10 VM on some panel opens, but i don't believe this is a bug we can fix. Checked the code here and there are no additional elements. It appears to be some kind of rendering error.

**Comment by johngruen** [comment]
Maybe if we just eyedropped the hex value as it's displayed rather than using hsla?

**Comment by johngruen** [comment]
I really really really think this is closed now
