### ISSUE TITLE
White space wrongly appears in the right side of Side View panel if it's pinned to the Overflow Menu

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#182]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.3.2

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Right click the "Open Side View" toolbar button and select the "Pin to Overflow Menu" context menu option.
3. Click the "More tools..." button and select the "Open Side View" tab.
4. Observe the Side View panel.

[Expected result]:
- The Side View's elements fully populate the panel's width.

[Actual result]:
- White space is displayed in the right side of the panel.

[Notes]:
- This issue is also reproducible if the scrollbar appears in the Side View panel.
- This issue is not reproducible on Mac OSes.
- Here is a screen recording with this issue:
![side view - white space - pinned panel](https://user-images.githubusercontent.com/31244235/38868145-c6dedbcc-424e-11e8-84f0-18805ea0894e.gif)

**Comment by Softvision-CristinaBadescu** [comment]
With the latest version of Side View 0.3.2 (custom built on 2018-04-18), two disabled scrollbar appear, on latest Nightly build 61.0a1 (Build ID: 0180418112600), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.
Considering this, I'm going to reopen the issue.

We've encountered a similar behavior for another experiment from Test Pilot: https://github.com/bwinton/SnoozeTabs/issues/403. Maybe @lmorchard  has some insight on what we can do about it?

**Comment by lmorchard** [comment]
I don't really have any insight - we closed that issue on SnoozeTabs after being unable to reproduce, so I never had a fix

**Comment by Softvision-CristinaBadescu** [comment]
I've managed to reproduce this issue using the latest Side View v0.3.2, on latest Nightly build 61.0a1 (2018-05-01) on Ubuntu 14.04 x64 and intermittent on Windows 10 x64 (I've managed to reproduce it 1 out of 10 tries). The white space appears only when the Side View button is pinned to the Overflow menu. 

However, I've noticed that the behavior is different: 
- on Ubuntu, the white space is displayed every time you open Side View from the Overflow menu.
- on Windows, the panel is correctly displayed after you access Side View for the second time from the Overflow menu.
Here is a screen recording with the issue: https://goo.gl/q5zt8u

Considering this I'm going to reopen the issue.

**Comment by johngruen** [comment]
now you've got me installing an ubuntu VM 😱

**Comment by fzzzy** [comment]
This does smell like a platform bug to me since it has different behavior on different platforms...

**Comment by Softvision-CristinaBadescu** [comment]
This issue is still intermittently reproducible using the latest Side View v0.3.2 (custom built on 2018-05-04), on latest Firefox release 59.0.3, using Windows 10x64 (it reproduces 2 out of 10 tries) and on Ubuntu 14.04 x64 (6 out of 10 tries).

I will file an upstream bug as soon as we clarify the situation encountered in #226 .

**Comment by Softvision-CristinaBadescu** [comment]
I've filed the issue here: [bug 1460252](https://bugzilla.mozilla.org/show_bug.cgi?id=1460252).
