### ISSUE TITLE
Tabs sections and websites wrongly overlap when you scroll down, if "Side View" is pinned to the Overflow Menu on Windows

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#183]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.3.2.

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.
- Have 21 tabs with content opened.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Right click the "Open Side View" toolbar button and select the "Pin to Overflow Menu" context menu option.
3. Click the "More tools..." button and select the "Open Side View" tab.
4. Scroll down and observe the behavior.

[Expected result]:
- The panel is correctly scrolled and no graphical artifacts are displayed.

[Actual result]:
- The tabs sections and the websites overlap.

[Notes]:
- This issue is also reproducible if you have websites in the "Recent Tabs" section.
- This issue is also reproducible if you don't have the Side View pinned to the Overflow menu. However it's not as severe, since only the last titles are overlapping.
- The graphical glitch disappears if you wait a couple of seconds after scrolling.
- Here is a screen recording with this issue:
![side view - broken ui](https://user-images.githubusercontent.com/31244235/38868211-fc406394-424e-11e8-80d5-82d6f75751a0.gif)

**Comment by johngruen** [comment]
Let's see if #180 fixes this

**Comment by Softvision-CristinaBadescu** [comment]
It seems that #180  has partially fixed this issue, since the behavior mentioned in the second note is still reproducible, with the latest Side View v0.3.2, on latest Nightly 61.0a1 (2018-04-19), on Windows 10 x64.
Here is a screen recording with the behavior:
![side view - glitch](https://user-images.githubusercontent.com/31244235/38997668-a947458c-43f6-11e8-9571-d944b213b11c.gif)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Side View v0.3.2, on latest Nightly build 61.0a1 (2018-04-30), on Windows 10 x64.
