### ISSUE TITLE
[Enhancement] Disable right click mouse events from the Side View panel

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/side-view#184]
[Notes]:
- Given that half of the options are greyed out and View Source opens a blank tab I suggest we remove the context menu altogether.
- "Save Page as" and "Select All" work as expected.

[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.3.2.

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.
- Have at least one tab opened.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Open Side View" button from the browser toolbar.
3. Right click the panel and observe the behavior.

[Expected result]:
- Nothing happens.

[Actual result]:
- A context menu is displayed.

[Additional Notes]:
- Here is a screen recording with this issue:
![disable right click events](https://user-images.githubusercontent.com/18304511/38870206-ce6c1128-4255-11e8-8300-e1a5154f0309.gif)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Side View v0.3.2, on latest Nightly build 61.0a1 (2018-04-25), on Windows 10 x64, Mac 10.13.4 and Ubuntu 14.04 x64.
