### ISSUE TITLE
The "Welcome" screen is wrongly displayed instead of the previously loaded website, after restarting the browser

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#192]
[Affected versions]:
- Firefox Nightly 61.0a1
- Side View 0.3.2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.
- Have the Side View Sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to any website.
2. Click the "Open Side View" toolbar button.
3. Restart the browser and observe the behavior.

[Expected result]:
- The website from step 2 is displayed.

[Actual result]:
- The "Welcome" screen is displayed.

[Notes]:
- This issue is also reproducible if you disable and re-enable the add-on.
- This issue is not reproducible if you switch or reopen the sidebar.
- Here is a screen recording with this issue:
![side view - welcome screen](https://user-images.githubusercontent.com/31244235/38992422-5a9adbfe-43e9-11e8-9349-2c185f320a8f.gif)

**Comment by wresuolc** [comment]
This is by design.
