### ISSUE TITLE
Clicking the "Give Feedback" link from the "Welcome" screen wrongly opens the link in the focused tab on Linux

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#199]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 3.2.0

[Affected Platforms]:
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false".

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to "about:addons" page -> Extensions tab and install the "Side View" add-on.
3. Click the "Give Feedback" hyperlinked text from the sidebar and observe the behavior.

[Expected result]:
- The link is opened in a new tab.

[Actual result]:
- The link is loaded in the focused one.

[Notes]:
- This issue is not reproducible with the "Give Feedback" button from the Side View pop up.
- This behavior is also reproducible for the "Watch Tutorial" hyperlinked text.
- Here is a screen recording with this issue:
![side view - give feedback](https://user-images.githubusercontent.com/31244235/39130201-3102c872-4715-11e8-96a4-b4a3dc489f2f.gif)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is still reproducible using the latest Side View v0.3.2, on latest Firefox Release 59.0.2, latest Nightly build 61.0a1 (2018-04-25), on Ubuntu 14.04 x64.

Considering this, I'm going to reopen the issue.

**Comment by ianb** [comment]
In #217 we moved to using `window.open()`, which I think should really fix this (though I can't confirm).

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using latest Side View v0.3.2, on latest Nightly build 61.0a1 (2018-05-01). However, I've encountered another issue, regarding the links from the "Welcome" screen, that I've filed it here #220 .
