### ISSUE TITLE
Side View panel goes blank when showing the browser window in full screen

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/side-view#210]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.3.2

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.
- The browser was previously resized.

[Steps to reproduce]:
1. Open the browser and click the "Open Side View" toolbar button.
2. Press "F11" key and observe the panel.

[Expected result]:
- The panel renders correctly with the fullscreen state.

[Actual result]:
- The panel goes blank.

[Notes]:
- This is also reproducible with the populated panel.
- Attached a screen recording of the issue:

![resize side view panel](https://user-images.githubusercontent.com/26000308/39297738-f4e942dc-494c-11e8-8e52-9263011331ec.gif)

**Comment by wresuolc** [comment]
We think this is also a platform bug.  Can you file a bug in bugzilla?  Thanks

**Comment by Softvision-CristinaBadescu** [comment]
Sure thing! We logged it here #[1457429](https://bugzilla.mozilla.org/show_bug.cgi?id=1457429).
