### ISSUE TITLE
Some of the options from context menu don't work when triggered from the sidebar

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/side-view#211]
[Notes]: 
- We also consider that "Open in sidebar" option shouldn't be displayed in context menu if the user has already opened the same page in sidebar.

[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.3.2

[Affected Platforms]:
- All Windows
- All Linux
- All Mac
 
[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.

[Steps to reproduce]:
1. Open the browser and navigate to a website (e.g. www.wikipedia.com).
2. Click on the "Open Side View" button from the right part of the address bar.
3. Right click on the website opened in Sidebar.
4. Click any of the following options and observe what happens next:
- "Save Page to Pocket" 
- "Select All"
- "View Page Source" 
- "Take a Screenshot" (not displayed for Release channel on Windows).

[Expected result]:
- Each option generates specific actions.
OR
- Options are not displayed in the context menu if they are not compatible with the Sidebar or, at least, they should be greyed out.

[Actual result]:
- Nothing happens, the options don't generate any response.

[Additional Notes]:
- See also: #[184 ](https://github.com/mozilla/side-view/issues/184)
- Attached a screen recording of the issue:

![side view context menu](https://user-images.githubusercontent.com/26000308/39311248-1ad6b5d8-4975-11e8-8956-cccd6e970b8e.gif)

**Comment by wresuolc** [comment]
This seems like a Firefox bug for sidebars?  We don't think there is anything we can do with those options

**Comment by wresuolc** [comment]
Can you file a bugzilla bug please? thanks

**Comment by Softvision-CristinaBadescu** [comment]
Sure thing! We logged it here #[1457432](https://bugzilla.mozilla.org/show_bug.cgi?id=1457432).
