### ISSUE TITLE
The private browsing warning is no longer displayed after being dismissed and the add-on reinstalled

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#212]
[Affected versions]:
- Nightly 61.0a1
- Side View 0.3.2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.
- Have the "xpinstall.signatures.required" pref set to "false".

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Open a Private Window ("Ctrl/Cmd + P" keys combination) and click the "Open Side View" toolbar button.
3. Dismiss the warning message.
4. Navigate to the "about:addons" page -> Extensions tab and click the "Remove" button.
5. Restart the browser and re-install the addon.
6. Open a Private Window and observe the "Open Side View" toolbar button.

[Expected result]:
- The button has the warning badge.

[Actual result]:
- The button has no badge.

[Notes]:
- This issue is also reproducible if you re-enable the add-on.
- The private browsing message from the Side View pop up is also no longer displayed.
- Here is a screen recording with this issue:
![sv- warning badge](https://user-images.githubusercontent.com/31244235/39314600-4bcd5a7c-497d-11e8-875d-d25d199957a8.gif)

**Comment by wresuolc** [comment]
We don't consider this a flaw.  Thanks for filing though!

**Comment by johngruen** [comment]
Let's address this in triage tomorrow. presumably this isn't a blocker since all users will get a new add-on tomorrow

**Comment by johngruen** [comment]
🤷‍♂️
