### ISSUE TITLE
The content loaded in the sidebar cannot be selected

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#214]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.3.2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to a website that has text and click the "Open Side View" action button from the address bar.
3. Hover over  a text from the sidebar and try to select it.
4. Observe the behavior.

[Expected result]:
- The cursor changes into a text caret and the text can be selected.

[Actual result]:
- The cursor is displayed as an arrow and the text can not be selected.

[Notes]:
- This issue is reproducible for both Desktop and Mobile site version.
- However, the images can be selected and dragged from the sidebar.
- Here is a screen recording with this issue:
![sv- text cannot be selected](https://user-images.githubusercontent.com/31244235/39365251-42d157fe-4a39-11e8-94fc-5f30c132fd3f.gif)

**Comment by johngruen** [comment]
This is probably upstream so we should file a bug there.

**Comment by johngruen** [comment]
@Softvision-CristinaBadescu will file a bugzilla bug and close this

**Comment by Softvision-CristinaBadescu** [comment]
Sure thing. I've filed it here: [bug 1460225](https://bugzilla.mozilla.org/show_bug.cgi?id=1460225).

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for fixing this! I have verified this issue and is no longer reproducible using the latest Side View v0.4.3 (custom built on 2018-05-24), on latest Nightly build 62.0a1, on Windows 10 x64, Mac 10.13.4 and Arch Linux 4.12. The text from the sidebar can now be selected.
