### ISSUE TITLE
The links from the "Welcome" screen are not working

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#220]
[Notes]:
- This issue is not reproducible if you install the add-on through "about:debugging" page.

[Affected versions]:
- Nightly 61.0a1
- Side View 0.3.2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false".

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to "about:addons" page -> Extensions tab and install the Side View add-on.
3. Click the "Give Feedback" hyperlinked text and observe the behavior.

[Expected result]:
- The link is opened in a new tab.

[Actual result]:
- The link is not opened.

[Additional notes]:
- This issue is also reproducible for the "Firefox Test Pilot" hyperlinked text.
- Here is a screen recording with this issue:
![sv- links not working](https://user-images.githubusercontent.com/31244235/39530752-49353f3c-4e32-11e8-960c-12fe07835c24.gif)

**Comment by ianb** [comment]
These all appear to be working now, except the tutorial (which isn't written yet), which we will do in #227
