### ISSUE TITLE
The "Give Feedback" button is no longer working

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#221]
[Affected versions]:
- Firefox 59.0.3 and up
- Side View 0.3.2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.
- Have one tab opened.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Open Side View" toolbar button.
3. Click the "Give Feedback" button and observe the behavior.

[Expected result]:
- The link is opened in a new tab.

[Actual result]:
- The link is not opened.

[Notes]:
- This issue is also reproducible if you try to access the button using the keyboard.
- Here is a screen recording with this issue:
![sv- give feedback button](https://user-images.githubusercontent.com/31244235/39535922-d0fe0b82-4e3d-11e8-9be9-83b05065615f.gif)

**Comment by ianb** [comment]
John fixed this in a recent PR

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Side View v0.3.2 (custom built on 2018-05-04), on latest Firefox Developer Edition 61.0b1, latest Firefox release 59.0.3, on Windows 10 x64, Mac 10.13.4 and Ubuntu 14.04 x64. The "Give Feedback" button is now working when it's being clicked or accessed using the keyboard.
