### ISSUE TITLE
Autoupdate does not appear to be working

### ISSUE THREAD

**Issue by johngruen** [mozilla/side-view#230]
Tried to do an update of the XPI from about:addons, but it didn't work...checked the XPI link and it was the new version. It appears something is off with our add-on updates

🤷‍♂️

**Comment by johngruen** [comment]
Stealing a QA label, bc this does indeed block launch

**Comment by johngruen** [comment]
@clouserw

**Comment by wresuolc** [comment]
Can you give me a copy of the XPI that won't update?

**Comment by johngruen** [comment]
@clouserw the one i got was just from the readme...let's push an update after tomorrow's standup and see what happens

**Comment by wresuolc** [comment]
Thanks.  I grabbed a copy and there is no update URL.  patch incoming
