### ISSUE TITLE
The sidebar cannot be resized to its maximum width using unsigned Side View build, on Nightly and Firefox Developer Edition

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#237]
[Notes]:
- This issue has been caused by [the fix](https://github.com/mozilla/side-view/pull/236) for #226  and it affects the QA for testing the resize functionality.
- Usually we test the custom builds because they contain the latest changes.

[Affected versions]:
- Firefox Nightly 62.0a1
- Firefox Developer Edition
- Side View 0.4.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.4.3 (custom built on 2018-05-09) installed.
- Have the Side View sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Drag the sidebar to its maximum width and observe the behavior.

[Expected result]:
- The sidebar is resized to its maximum width.

[Actual result]:
- The sidebar cannot be resized to its maximum width.

[Additional notes]:
- This issue is not reproducible wit the pre-built add-on from here: https://github.com/mozilla/side-view.
- This issue is not reproducible on Firefox Release 59.0.2.
- Here is a screen recording with this issue:
![sv - resize does not work for unasigned build](https://user-images.githubusercontent.com/31244235/39805332-3f6f2b64-537f-11e8-96db-6ec6081c39a9.gif)

**Comment by wresuolc** [comment]
This happens because of the signing.  It's not something we can fix and shouldn't show up in the signed builds.

**Comment by Softvision-CristinaBadescu** [comment]
It seems that there is a workaround for this issue: if I set the following prefs (we use these to test Firefox Screenshots dev version), I can resize the sidebar to its maximum width:

"xpinstall.signatures.required" to false
"extensions.legacy.enabled" to true
"extensions.install.requireBuiltInCerts" to false.
