### ISSUE TITLE
Certain social media favicons are not displayed in the "Recent Tabs" section in Private Windows

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#238]
[Affected versions]:
- Firefox 59.0.3 and up
- Side View 0.4.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.4.3 (custom built on 2018-05-09) installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to "https://twitter.com/" and send the link to the sidebar.
3. Open a Private Window.
4. Click the "Open Side View" toolbar button and observe the Twitter favicon from the "Recent Tabs" section.

[Expected result]:
- Twitter's favicon is correctly displayed.

[Actual result]:
- Twitter's favicon is not displayed.

[Notes]:
- This issue is also reproducible for the LinkedIn favicon.
- The behavior is different depending on the OSes:

- On Windows OSes, this issue is also reproducible for the "Current Tabs" section.
- On Mac OSes the issue is not reproducible if the websites are sent to the sidebar, but it still affects the future opened Private Windows.
- On Linux OSes, this issue is not reproducible for the LinkedIn favicon if the website is loaded in the sidebar. However, the Twitter favicon is displayed in the "Current Tabs" section, but not in the "Recent Tabs".

- Here is a screen recording with this issue:
![sv - social media icons not displayed in private windows](https://user-images.githubusercontent.com/31244235/39821533-23326330-53b1-11e8-9387-dec6863b19e6.gif)

**Comment by wresuolc** [comment]
The text is still there which is the important part.  We're going to close this.
