### ISSUE TITLE
Recent Tabs not populating upon tab close

### ISSUE THREAD

**Issue by htwyford** [mozilla/side-view#242]
I've seen this on Firefox 59.0.2, Firefox 60.0 and Nightly 62.0a1 (2018-05-10) with Side View 0.4.3066 on Mac.

Open a new Firefox profile. Notice the Sideview popup is in its default empty state. Open some tabs and then close them. Recent tabs is not populated.

Here's a (very fast, apologies) screenrecording:

![no_recents](https://user-images.githubusercontent.com/1606496/39890334-75aaffde-5468-11e8-9c3e-5c9cb72e5d80.gif)

**Comment by fzzzy** [comment]
@htwyford That's actually how it is supposed to work, it only shows tabs that were recently sent to the sidebar. I think we should change the wording to be less confusing though.

**Comment by htwyford** [comment]
Gotcha. Would "Recently Opened in Side View" might suit it? It's a bit verbose but I think an average user(/me) might think that anything along the lines of "Recently Opened", "Recent Tabs", "Recents" is referring to something else.

**Comment by fzzzy** [comment]
I think that makes more sense. When it was called Tab Split, it said "Current tabs" and "Recent splits" or something similar and it made more sense then.

**Comment by htwyford** [comment]
Would a "pin to top" system not work better in this context? I imagine users would get the most use out of being able to pin frequently-split sites (Youtube, Twitter?) to the top of the list rather than a list of recents

**Comment by htwyford** [comment]
Closing because it's a non-issue

**Comment by fzzzy** [comment]
After thinking about this more, maybe just labeling it "Recent" would be simple and clear enough?
