### ISSUE TITLE
The Side View toolbar button is not displayed after reinstalling the experiment, if it was previously removed from the Toolbar

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#246]
[Affected versions]:
- Firefox 60.0 and up
- Side View 0.4.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.4.3 installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Right click the "Open Side View" toolbar button and select the "Remove from Toolbar" option.
3. Navigate to "about:addons" page -> Extensions tab and remove the Side View experiment.
4. Restart the browser and reinstall the experiment.
5. Observe the behavior.

[Expected result]:
- A new "Open Side View" toolbar button is displayed.

[Actual result]:
- The "Open Side View" toolbar button is not displayed.

[Notes]:
- The issue is still reproducible even if you don't restart the browser.
- This issue is reproducible on Firefox Release 60.0, with the add-on installed through "about:debugging" page.
- This issue is not reproducible for the "Open Side View" action button from the address bar, after restarting and reinstalling the experiment.
- Here is a screen recording with this issue:
![sv - no toolbar button after reinstall](https://user-images.githubusercontent.com/31244235/39995924-764389b8-5786-11e8-84b3-456275a3ebc3.gif)

**Comment by wresuolc** [comment]
Thanks for filing. We think this is ok behavior.
