### ISSUE TITLE
The unsigned build of Side View is not working if it's installed through the "about:debugging" page

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#247]
[Affected versions]:
- Nightly 62.0a1
- Side View 0.4.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Download the [Side View v0.4.3](https://drive.google.com/file/d/1a0j8Dk6-gR03tWngjg9OQJKdGEU2UyHn/view?usp=sharing) custom built on 2018-05-14.

[Steps to reproduce]:
1. Open the Firefox browser.
2. Navigate to the "about:debugging" page and load the downloaded ".zip" from the prerequisites.
3. Observe the behavior.

[Expected result]:
- The Side View experiment is installed: 
The Side View sidebar is opened.
The "Open Side View" toolbar button and action button from the address bar are displayed.

[Actual result]:
- The Side View experiment seems to be installed, but is not working:
The Side View sidebar is not opened.
The "Open Side View" toolbar button and action button from the address bar are not displayed.

[Regression]:
Last good revision: 8af38d67ffb3efb94f619b1f5b00ccaa19609263
First bad revision: ad6caf1d4d23bc139562493ffbb8c0f199ed0b30
Pushlog: https://goo.gl/2UZj69

From the pushlog it seems that bug 1385057 has caused this issue.

[Notes]:
- I've logged a Bugzilla issue here: [bug 1461309](https://bugzilla.mozilla.org/show_bug.cgi?id=1461309).
- This issue is not reproducible using the signed xpi, from the GitHub repository: https://github.com/mozilla/side-view.
- The attached Side View build is cloned from the GitHub repository (https://github.com/mozilla/side-view).
- The experiment is displayed in the "about:addons" page, even though it's not working.
- Here is a screen recording with this issue:
![sv - not working - installed through debugging](https://user-images.githubusercontent.com/31244235/39998632-5787bb44-578f-11e8-9d31-512ccfcff4ce.gif)

**Comment by wresuolc** [comment]
The addon.xpi in the top level directory should work.
