### ISSUE TITLE
The browser window's UI is not entirely visible if it's resized to the minimum width and the sidebar is resized to its maximum width

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#256]
[Affected versions]:
- Firefox 60 and up
- Side View 0.4.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View version 0.4.3 installed.
- Have one tab open.
- Have the Side View sidebar resized to its maximum width.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Observe the window's UI as you resize it to its minimum width.

[Expected result]:
- All of the window's UI is constantly visible.

[Actual result]:
- As you reach towards the window's minimum width the browser window buttons ("Minimize", "Maximize", "Close"), tab strip, toolbar, vertical scrollbar and the page's content are no longer visible.

[Regression]:
It seems that the behavior is not as severe in Nightly 42.0a1: only the browser specific buttons are hidden, but not the OS specific ones. I've managed to find a regression window using the Mozregression tool. Here are the results:
Pushlog: https://goo.gl/ojScUS

After talking with RyanVM we suspect that bug 1173725 probably affected this issue.

[Notes]:
- This is an upstream bug, which I've filed it here #[1462274](https://bugzilla.mozilla.org/show_bug.cgi?id=1462274), and it affects the Side View Sidebar also.
- On Mac and Linux OS'es all of the above elements are affected except the browser window's buttons.
- Here is a screen screen recording with this issue:
![sv- window ui](https://user-images.githubusercontent.com/31244235/40167943-03b60d16-59cb-11e8-8554-92d283bac459.gif)

**Comment by wresuolc** [comment]
This is the same behavior without our extension so closing this
