### ISSUE TITLE
The "x" button for the tabs from "Recent" section does not have a descriptive tooltip

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#261]
[Affected versions]:
- Firefox 60.0.1 and up
- Side View 0.4.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View version 0.4.3 installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to a website and click the "Open Side View" action button.
3. Click the Side View toolbar button.
4. Hover the "x" button from the displayed tab from the "Recent" section.

[Expected result]:
- A descriptive tooltip (eg. "Dismiss") is displayed.

[Actual result]:
- No tooltip is displayed.

[Notes]:
- Here is a screen screen recording with this issue:
![sv - x button descriptive tooltip](https://user-images.githubusercontent.com/31244235/40475938-7603e5f2-5f4b-11e8-97ed-a736d16d1163.gif)

**Comment by johngruen** [comment]
"Remove from recent"

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for fixing this! The issue is no longer reproducible using the latest Side View v0.4.3, on latest Nightly build 62.0a1 (2018-05-29), on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12. When you hover the "x" button, the "Remove Tab from Recent List" tooltip is displayed.
