### ISSUE TITLE
The "x" button for the tabs from "Recent" section is wrongly rendered when Dark Theme is enabled

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#262]
[Affected versions]:
- Firefox 60.0.1 and up
- Side View 0.4.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View version 0.4.3 installed.
- Have the Dark Theme enabled.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to a website and click the "Open Side View" action button.
3. Click the Side View toolbar button and observe the "x" button from the displayed tab in the "Recent" section.

[Expected result]:
- The button is rendered respecting the dark theme.

[Actual result]:
- A white space is displayed where the button is positioned.

[Notes]:
- Here is a screen screen recording with this issue:
![sv - dark theme button](https://user-images.githubusercontent.com/31244235/40482211-ac8af1a4-5f5c-11e8-87df-0d14530dbe43.gif)

**Comment by Softvision-CristinaBadescu** [comment]
Also, I have noticed that the tab is not highlighted if you hover the "x" button.

**Comment by fzzzy** [comment]
@htwyford Any ideas on how to fix this? Nothing I change in the css seems to help.

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for fixing this! The issue is no longer reproducible using the latest Side View v0.4.3, on latest Nightly build 62.0a1 (2018-05-29), on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12.
