### ISSUE TITLE
Add buttons to the bottom of the sidebar?

### ISSUE THREAD

**Issue by WesleyBranton** [mozilla/side-view#278]
Three buttons should be added to the bottom of the sidebar (back, refresh/stop, forward). It could be done by injecting fixed Javascript buttons each time the page loads.

I've done a rough mockup of what I think the buttons should look like. Obviously the font needs to be adjusted and it needs some fine tuning, but this is the rough layout I think we should have:

![mockup](https://user-images.githubusercontent.com/6621449/41067329-28185388-69b3-11e8-8354-455b1c9a3421.PNG)

Thoughts?

**Comment by johngruen** [comment]
We TRIED to to this, but the APIs as they are currently construed make it impossible. I'm going to close this for now since it's non-actionable, but we can revisit as events warrant

**Comment by gabriel-r** [comment]
It's been a while, is this still blocked by API limitations?
