### ISSUE TITLE
Links clicked in sidebar are opening in main window

### ISSUE THREAD

**Issue by codingTheHole** [mozilla/side-view#282]
Occurring at news.bbc.co.uk

**Comment by gk159yo** [comment]
also at https://www.wuxiaworld.com/novel/sovereign-of-the-three-realms/sotr-chapter-47
Try clicking the right arrow key:
![image](https://user-images.githubusercontent.com/18729755/41198607-9671708c-6c36-11e8-8528-8d68fb373144.png)

This is a big bummer... :disappointed:

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for reporting this. However, this is how Side View is working for the moment: some links will be opened inside the sidebar (https://github.com/mozilla/side-view/issues/114), and some will be opened in the main window (https://github.com/mozilla/side-view/issues/107).

@gk159yo, when I click the right arrow key, the next chapter is loaded in the sidebar. What is the issue that you are encountering?
