### ISSUE TITLE
Cross browser able?

### ISSUE THREAD

**Issue by EC-O-DE** [mozilla/side-view#287]
I so want this! Is it far from being cross browser able?

Vivaldi / Yandex / Opera ?

**Comment by ExE-Boss** [comment]
It might sort-of work on Opera, as Opera also supports [sidebars](https://developer.mozilla.org/Add-ons/WebExtensions/user_interface/Sidebars)

**Comment by EC-O-DE** [comment]
That old sidebar hopefully deprecated soon and moved to the new Reborn Sidebar.

**Comment by johngruen** [comment]
Hey since we're not gonna build stuff for other browsers i'm gonna close this, but as @ExE-Boss point out, this might just sorta work accidentally in Opera. Who knows?
