### ISSUE TITLE
Inbox by Google is inaccessible

### ISSUE THREAD

**Issue by ELowry** [mozilla/side-view#290]
When trying to access https://inbox.google.com/ inside a side view I get the following error message:

> Inbox cannot be accessed from browsers on this device. Please download the Inbox app or open Gmail instead.

**Comment by johngruen** [comment]
Hey @ELowry look in hte side-view menu button, there's an option to request desktop sites. Inbox works that way (but the site itself is not optimized for narrow windows unfortunately)
