### ISSUE TITLE
[Bug] Firefox Containers 

### ISSUE THREAD

**Issue by bunnybooboo** [mozilla/side-view#292]
I love this Test Pilot but have observed a bug.

I have additionally `Containers on the Go` addon installed along with `Firefox Multi-Account Containers` - where Slack is selected to "always open in" a specific container. 

This is where it gets pretty confusing! Please bear with me.

I start with an already containered & logged in instance of Slack (in its preselected default container), and then ADDITIONALLY:

In a new (non-default) container tab navigate to a Slack instance>> sign in >> authenticate via WebAuthn-U2F (hardware 2FA) >> click toolbar icon `Open Side View` >> click `Ask for Desktop Site` >> (despite signing in on the originating tab it loses auth) >> click `Sign in with Auth0`

.. a new tab is opened. I'm presented with the choice of opening in the current container or the default container. There is no indication of which container the sideview is already in. Testing both of these did not allow the Side View to log in. Side View appears isolated from these containers as #288 might indicate.

Performing those same steps, but in a regular (non-containerized) tab, allows me to log into the side view. 

Based on the previous attempts, I would expect any other containers to be unaffected. HOWEVER, when I then log out in this Side View and close the sidebar, and then navigated to the already open (default) container for Slack and then switching its view over to Side View, the Auth0 stays connected. I expected this attempt to perform just as it did *before* the successful login in a non-containerized tab & Side View.

This indicates to me that either:

1. this is unexpected behavior where the containers isolation model does not extend to Side View use - as it inherited behavior from another (non-containerized) tab
2. OR this additional (non-obvious) step is needed for all containerized tabs to function as expected

**Comment by johngruen** [comment]
Hey @bunnybooboo currently the underlying APIs don't support containers in sidebar. Not perfect, but not something we can fix in our codebase. I'll file a bug with the add-ons team 👍
