### ISSUE TITLE
Local files

### ISSUE THREAD

**Issue by Camwyn** [mozilla/side-view#298]
I'd like to be able to open a local file in the side-view - but whenever I try it just loads the active tab.

Example usage: I open a mock (image file) in the side-view to compare to the site I am making changes to.

Is there something I'm missing or is this a good time for a feature request?

**Comment by johngruen** [comment]
Huh. We did some checking and unfortunately there are security restrictions in the webExtensions API that restrict loading of local content in the sidebar.

**Comment by Camwyn** [comment]
Thanks @johngruen - at least I know it's not just something I missed.
