### ISSUE TITLE
Youtube videos stuck in a short loop

### ISSUE THREAD

**Issue by Geolim4** [mozilla/side-view#299]
When watching a Youtube video in side view the video is stuck on the first 0.5sec that render in a sort of loop. I tried by disabling all my other extension one by one but I'm still having the issue.

However the sound is still playing correctly.

**Comment by johngruen** [comment]
Huh, that's a new one. Can you tell us a little about the system you're on and version of Firefox?

If you're inclined, could you check and see if creating a fresh profile fixes the issue?

**Comment by Geolim4** [comment]
I'm on Win10x64 with Firefox 62.0-b4x64.

I can test on another profile (my friend one) on a different computer to check if it could be a module conflict or some kind of bug.

**Comment by Geolim4** [comment]
No issue on another computer, guess it's just a conflict with some 3rd party extension...

**Comment by billmetangmo** [comment]
I got the same issue sometimes. When I reload the side view ( copy youtube video url at cuurent time, open it in a new tab and throws it on side view) , it works well but after a certain period, i have it again ( the period seems to not be fixed).

 Firefox version : 61.0.1 (64-bit)
 Operating System: Microsoft Windows 7 Enterprise Edition

**Comment by billmetangmo** [comment]
I got a procedure to repeat this issue . 

1/ Open a firefox tab 
2/ Open a youtube video on this tab
3/ Throw it in side view
4/ Open another website ( in my case twitter)
5/ After a small period, the video stucks in a short loop  

Can you reproduce it @Geolim4 ?

**Comment by Geolim4** [comment]
@billmetangmo Yeah but it's specific on a computer I don't have this issue on another one.

**Comment by billmetangmo** [comment]
Ya, you're right. It works well on my another computer with Windows 10.
Thanks @Geolim4
