### ISSUE TITLE
The Side View sidebar context menu is not stylized correctly

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#301]
[Affected versions]:
- Nightly 63.0a1, Build ID: 20180709100247
- Side View 0.4.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View version 0.4.3 installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to a website.
2. Click the "Open Side View" action button.
3. Right click a hyperlinked element from the Side View sidebar.
4. Observe the behavior.

[Expected result]:
- The context menu is correctly displayed.

[Actual result]:
- The context menu background is transparent, the fonts are very large and the "Open link in sidebar" icon is huge.

[Regression]:
This issue is not reproducible using the latest Firefox Release 61.0.1 or Firefox Beta 62.0b6. Considering this, I've managed to find a regression window using the Mozregression tool.
Here are the results:
Last good revision: 626eb82739e7be8e09e130db28fa1c17f7d5340e
First bad revision: 953772c799a689203de16cb4fab6d577f77a1002
Pushlog: https://goo.gl/aB3QNk
From the pushlog, it looks like Bug [1470870](https://bugzilla.mozilla.org/show_bug.cgi?id=1470870) has caused this issue.

[Notes]:
- Other webextensions icons are also affected (eg. Firefox Screenshots "Take a Screenshot" option).
- Here is a screen recording with this issue:
![sv- context menu not properly stylized](https://user-images.githubusercontent.com/31244235/42499754-44efba38-8438-11e8-9cbb-e4a8162c6980.gif)

**Comment by johngruen** [comment]
Let's reopen the upstream bug!

**Comment by Softvision-CristinaBadescu** [comment]
Sure thing. It's being tracked here: [bug 1474631](https://bugzilla.mozilla.org/show_bug.cgi?id=1474631).

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible on the latest Nightly build 63.0a1 (Build ID: 20180711221812). Verified on Windows 10 x64, Mac 10.13.5 and Arch Linux 4.12.
