### ISSUE TITLE
Any way to test this feature in testpilot without the spyware?

### ISSUE THREAD

**Issue by nukeop** [mozilla/side-view#302]
I noticed that enabling this in testpilot also enables extensive data gathering. Is there any way to disable that while using the side view feature?

**Comment by johngruen** [comment]
so, yeah we respect DNT in the browser, so if you have that enabled we aren't collecting. 

Or, you can just clone this repo and rip out data collections and run the add-on locally.

**Comment by ianb** [comment]
Here's the Do Not Track pref:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/44390/42521157-b3ea1e16-842d-11e8-9095-6658bc60f90c.png">

**Comment by nukeop** [comment]
Cool, I didn't know that can also influence what extensions send. Great addon.

**Comment by ianb** [comment]
Do Not Track doesn't effect every extension, but our analytics code looks at that pref (https://github.com/mozilla/testpilot-ga/blob/7bd77872036ba6022915868481aed52297fb079d/src/TestPilotGA.js#L194)
