### ISSUE TITLE
Opens the same sidebar page on all browser windows?

### ISSUE THREAD

**Issue by tmikaeld** [mozilla/side-view#304]
Opening a page in the sidebar opens the same sidebar page on all browser windows, is that really how it's supposed to function? I've restarted firefox as well, same behavior.

**Comment by glawrence** [comment]
Personally I really like this as it allows me to keep an eye on a specific page and see any updates there while generally browsing. In my case the side view displays the progress of a build job that takes a couple of minutes, so I can view twitter and other pages but keep a close eye on my build.

Maybe the answer is a Preference option?

**Comment by tmikaeld** [comment]
> Maybe the answer is a Preference option?

That would certainly be the best!

**Comment by Catmato** [comment]
I understand it functioning like this with tabs, but propagating to all browser windows is baffling.

**Comment by ianb** [comment]
This is a bug, issue #272 is to fix this bug. Closing this one as a duplicate
