### ISSUE TITLE
[Feature Request] Add an option to reload Side View page

### ISSUE THREAD

**Issue by glawrence** [mozilla/side-view#305]
I cannot find a way to reload the page in the Side View, sometimes I like or need to refresh it

**Comment by Softvision-CristinaBadescu** [comment]
We used to have a "Home", "Reload" and "Back" buttons, but due to limitations of the API we don't support this feature, at least for the moment.

**Comment by pepebe** [comment]
I don't think this should be closed. Label it as a feature request and let it open until somebody comes up with a good compromise. 

At the least people looking for this problem will find out that they are not too stupid to do it.

Talking about solutions:

Would it be possible to list the current side view page inside the side view menu in the top right corner? Right now you can only load the original page or ask for a desktop/mobile version of the original page.
