### ISSUE TITLE
[BUG] Unable to close modal popup in gdocs

### ISSUE THREAD

**Issue by teonbrooks** [mozilla/side-view#309]
Sorry if this is a dup, didn't see it among the issues. noticed that I cannot close the bottom banner that pops up when you send a google doc to sidebar.

![sideview](https://user-images.githubusercontent.com/1578674/42967169-67e5cb40-8b6d-11e8-9cbb-b12c51ce0b76.gif)

**Comment by fzzzy** [comment]
I hadn’t seen this before. You can probably fix it by switching to the desktop view. We should probably load google docs in desktop view by default.

**Comment by teonbrooks** [comment]
the request for desktop mode did make the popup go away and you are able to edit the doc there too which is cool. however, the mobile view actually looks significantly better in the sidebar than the desktop view.

**Comment by ianb** [comment]
We can't really fix Google Docs, I'm afraid
