### ISSUE TITLE
Audit add-on permissions

### ISSUE THREAD

**Issue by ianb** [mozilla/side-view#314]
I'm not sure we need all the permissions we have. Maybe we do, I'm just unconvinced.

Here's what we have:

- [ ] activeTab
- [ ] tabs
- [ ] <all_urls>
- [x] storage (needed to support persistent desktop flag)
- [x] contextMenus (needed for the context menu)
- [x] webRequest (needed for user-agent header)
- [x] webRequestBlocking (also needed for user-agent header)
- [x] bookmarks (needed to open bookmarks)
- [x] management (needed for dark mode)

**Comment by fzzzy** [comment]
I feel like management permission is a lot to ask just for dark mode. Perhaps we could talk to whomever did dark mode to see if we could respect dark mode in a less intrusive way.

**Comment by ianb** [comment]
I'm pretty sure we're at minimal permissions now
