### ISSUE TITLE
An item stored using storage.sync may fails to sync because it exceeds the `QUOTA_BYTES_PER_ITEM` limit

### ISSUE THREAD

**Issue by rpl** [mozilla/side-view#328]
This issue as been filed on bugzilla as
- [Bug 1484968 - Sync errors: extension-storage fails with "Insufficient Storage"](https://bugzilla.mozilla.org/show_bug.cgi?id=1484968)

From a brief look to the storage.sync API calls that are currently used in the side-view extensions, it seems that `desktopHostnames` is the only item that could grow in side until it reaches the `QUOTA_BYTES_PER_ITEM` limit (See [Bug 1484968 Comment 1](https://bugzilla.mozilla.org/show_bug.cgi?id=1484968#c1) and [Bug 1484968 Comment 3](https://bugzilla.mozilla.org/show_bug.cgi?id=1484968#c3)).

**Comment by ianb** [comment]
I did a quick look to remind myself what we're saving: `recentTabs` is url/title/favicon for the last 5 sites. `desktopHostnames` is an object with domains as keys. It's unbounded, though it only gets added to when someone hits the Ask for Desktop Site button. It would seem surprising if it became problematically large.

Maybe faviconUrl could be a data URL or something unwieldy?
