### ISSUE TITLE
Request Data Review

### ISSUE THREAD

**Issue by marniepw** [mozilla/side-view#356]
Please answer the questions in this: [https://github.com/mozilla/data-review/blob/master/request.md](https://github.com/mozilla/data-review/blob/master/request.md)

Answer them in/by filing a bugzilla ticket. See full instructions here (look at section Step 1: Submit Request): [https://wiki.mozilla.org/Firefox/Data_Collection](https://wiki.mozilla.org/Firefox/Data_Collection)

NI Rob Rayborn (rrayborn) in the bugzilla bug. We'll need to get this started very soon to hit the Oct 29 launch date.

**Comment by ianb** [comment]
Requested in [Bug 1501436](https://bugzilla.mozilla.org/show_bug.cgi?id=1501436)
