### ISSUE TITLE
Confirm survey links work for engaged and non-engaged users

### ISSUE THREAD

**Issue by ianb** [mozilla/side-view#371]
In the PHD we specify that there are different surveys for people who did and didn't use Side View.

Right now we have one `?reason=expired`, but we also send other parameters that indicate if the user used Side View (onboarded, panel_days). These should be enough, but we should confirm this with @johngruen

**Comment by johngruen** [comment]
`reason=control, expired, user-disabled, midway`

```
onboarded: 0,
panel_days: 0,
uri_count: 0,
```
