### ISSUE TITLE
Allow for desktop view in side view

### ISSUE THREAD

**Issue by Elbullazul** [mozilla/side-view#375]
Hello,

It would be nice to be able to toggle between desktop and mobile views in side view, because some websites (most notably messenger.com) don't load what they show on desktop when using it on mobile. Here's an example:

![sidebar messenger](https://user-images.githubusercontent.com/15310985/47392517-d93ac980-d6ea-11e8-975e-4487f4af0815.png)

the side view (left) loads the mobile version while the normal view (right) loads the desktop-but-responsive website.

It would especially be useful for extensions of this kind: https://addons.mozilla.org/en-US/firefox/addon/fb-messenger-as-a-sidebar/

**Comment by fzzzy** [comment]
This is already implemented. If you press the side view button, there is a "Ask for Desktop Site" button.

**Comment by Elbullazul** [comment]
oops, you're right, I hadn't noticed. Thanks for pointing it out
