### ISSUE TITLE
[Shield] The addon is wrongly displayed on the about:addons page

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/side-view#385]
[Notes]:
- More info about this can be found [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1365349#c3).

[Affected versions]:
- Firefox Release Version 63.0.1, Build ID 20181030165643
- Firefox Nightly Version 65.0a1, Build ID 20181104220100

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The side-view-shield@mozilla.org-0.5rc3-signed.xpi is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to about:addons and observe the "Extensions" section.

[Expected result]:
- The addon is not displayed in the about:addons page.

[Actual result]:
- The addon is displayed.

[Additional Notes]:
- This issue is also reproducible with the side-view-control@shield.mozilla.org-0.1-signed.xpi.
- I have attached a screenshot of the issue:
![aboutaddons](https://user-images.githubusercontent.com/40393891/47998829-41d16f80-e109-11e8-93f8-12b23e06e211.png)

**Comment by ianb** [comment]
@mythmon says: "in order to have your add-on hidden in about:addons, you have to set `"hidden": true` in your `manifest.json`, if I recall correctly"

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using side_view-0.5rc5 on Windows 10 x64 using Firefox Nightly Version 65.0a1, Build ID 20181113100051 and Release Unbranded Version 63.0.1, Build ID 20181030165643.
Considering this I will mark this issue as verified fixed.
