### ISSUE TITLE
[Shield] The addon wrongly remains installed after 4 weeks

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/side-view#386]
[Affected versions]:
- Firefox Release Version 63.0.1, Build ID 20181030165643
- Firefox Nightly Version 65.0a1, Build ID 20181104220100

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The side-view-shield@mozilla.org-0.5rc3-signed.xpi is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Change the system time to 4 weeks in the future and restart the browser.
3. Observe the tabstrip.
4. Navigate to about:support and observe the "Extensions" section.

[Expected result]:
- Step 3: A survey is opened in a new tab.
- Step 4: The addon is not displayed in the about:support page.

[Actual result]:
- Step 3: The survey is not triggered.
- Step 4: The addon is still displayed.

[Additional Notes]:
- This issue is also reproducible with the side-view-control@shield.mozilla.org-0.1-signed.xpi.
- The addon sends the "exit" and "expired" pings only after 6 weeks, but remains installed.
- I have attached a screenshot of the issue:
![expire](https://user-images.githubusercontent.com/40393891/48002842-629fc200-e115-11e8-9d5f-2f77bdd14ef2.gif)

**Comment by johngruen** [comment]
I think we have the study set for 42 days

**Comment by ianb** [comment]
Actual uninstalling specified in #391

**Comment by Softvision-PatriciuPop** [comment]
This issue is still reproducible using the control and the elective-onboarding add-ons on Windows 10 x64, Arch Linux and Mac 10.13.3 using Firefox Nightly Version 65.0a1, Build ID 20181107100135. The addon is not removed from the about:support page after the 4 weeks have passed. No survey is triggered for the users in the control group and for the users that did not engage with Side View from the elective_onboarding branch.

This issue could not be verified on Firefox Release because the addon was signed with a dev key.

**Comment by Softvision-PatriciuPop** [comment]
This issue is still reproducible using the control add-on on Windows 10 x64, Arch Linux and Mac 10.13.3 using Firefox Nightly Version 65.0a1, Build ID 20181107100135. The control add-on is not removed after expiration and it's survey is not triggered. Considering this I will reopen the issue.

**Comment by johngruen** [comment]
@ianb ^

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using side_view-0.5rc5 on Windows 10 x64 using Firefox Nightly Version 65.0a1, Build ID 20181113100051 and Release Unbranded Version 63.0.1, Build ID 20181030165643.
Considering this I will mark this issue as verified fixed.
