### ISSUE TITLE
[Shield] The Side View doorhanger is not triggered after finishing the onboarding flow

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/side-view#387]
[Affected versions]:
- Firefox Release Version 63.0.1, Build ID 20181030165643
- Firefox Nightly Version 65.0a1, Build ID 20181104220100

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The side-view-shield@mozilla.org-0.5rc3-signed.xpi is available.

[Steps to reproduce]:
1. Open the browser with a new profile.
2. Install the Side View addon. 
3. Click the Side View button from the Toolbar.
4. Click the "Next" button 3 times.
5. Click the "Done" button and observe the behavior.

[Expected result]:
- The onboarding is dismissed and the "Recent" and "Current Tabs" section is displayed.

[Actual result]:
- The onboarding is dismissed.

[Notes]:
- I have attached a screenshot of the issue:
![peek 2018-11-05 15-57](https://user-images.githubusercontent.com/18304511/48002240-a72a5e00-e113-11e8-8bc8-b000a1ee9f12.gif)

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using side_view-0.5rc5 on Windows 10 x64 using Firefox Nightly Version 65.0a1, Build ID 20181113100051 and Release Unbranded Version 63.0.1, Build ID 20181030165643.
Considering this I will mark this issue as verified fixed.
