### ISSUE TITLE
Side-view not able to show full width of YouTube video 

### ISSUE THREAD

**Issue by aexley** [mozilla/side-view#417]
When moving a YouTube page to side-view, the sidebar width doesn't expand far enough to view the entire video width.

**Comment by Palciny** [comment]
You can expand a side view yourself.

![image](https://user-images.githubusercontent.com/15854440/52330274-587faf00-29f5-11e9-9e64-11dead461528.png)

**Comment by mjfa12** [comment]
Request mobile site and the you will be able to see the whole video.  Using the desktop site cuts off a portion of the video for me as well.  This only became a problem when the limited the ability to move the side bar width.
