### ISSUE TITLE
Overriding max width via userChrome.css not possible anymore

### ISSUE THREAD

**Issue by derscott** [mozilla/side-view#457]
Hi,

I really like the extension. For webpages, it would be more convenient to be able to increase the maximum size the panel can be dragged to. I've tried to accomplish this using this tutorial, but it does not seem to be working anymore:
https://dev.to/semanticdata/unlock-the-sidebar-width-in-firefox-22p0

I also tried to use `#sidebar` instead of `#sidebar-box` as a selector, without success (some website mentioned that with Firefox 107, the selector name had been changed).

**Comment by jaredhirsch** [comment]
See if this fixes your issue: https://www.reddit.com/r/FirefoxCSS/comments/yw6eek/sidebar_minwidth_0px_important_doesnt_work/

Closing in hopes it does; feel free to reopen if not 🍻
