### ISSUE TITLE
side bar support for googledoc? 

### ISSUE THREAD

**Issue by chrisdane** [mozilla/side-view#458]
Hi

In Firefox 128.0.3 (on a PC, not phone) a googledoc (i.e. https://docs.google.com/document/...) works as expected in a normal tab.

When I right-click on that tab -> 'Open in sidebar' (side-view 0.4.6424resigned1), the left side bar opens and displays the same page. Ok.

However, this side bar googledoc looks very different: I cannot edit the document (as if logged out the google account, but that's not indicated anywhere), comments are abbreviated as e.g. '[a]' and extended at the bottom of the page, figures are shown in very poor quality, and at the bottom there is a popup suggesting to use the google app. In this popup, there are two buttons (yes/no) but both are unresponsive when I click on them.

Thanks for help and cheers,
Chris

**Comment by jaredhirsch** [comment]
This weird behavior is a side effect of the add-on applying a mobile user agent string to stuff that loads in the side view.

The way to fix this is to load the page in desktop mode instead.

Step 1: add the side view toolbar button to the toolbar.

* click on the addons toolbar button to open the addons menu
* click the gear icon next to the side view entry
* then click "pin to toolbar"

Should look something like this:

<img width="414" alt="Screenshot 2024-08-16 at 4 20 23 PM" src="https://github.com/user-attachments/assets/d2628c4b-0bb8-4b06-9032-61dee7027ed4">

Now you should have a side view toolbar button.

Step 2: Click the side view toolbar button, then down at the bottom of the popup menu, click "Ask for Desktop site".

Should look like this:

<img width="352" alt="Screenshot 2024-08-16 at 4 28 01 PM" src="https://github.com/user-attachments/assets/250f8b46-82ce-4fde-9829-bddf2d4db980">

Step 3: Send your Google Doc to the side view.

You should now see the desktop version of GDocs in the sidebar:

<img width="700" alt="Screenshot 2024-08-16 at 4 25 51 PM" src="https://github.com/user-attachments/assets/e118a995-40ea-4532-bbcd-11a5cb88b9e5">

Closing, but feel free to reopen if you still have problems getting this to work.
