### ISSUE TITLE
[Feature Request] retracktable sidebar that contains the icons for the websites we use

### ISSUE THREAD

**Issue by arturfmmendes** [mozilla/side-view#465]
Sidebar just like Opera GX does for Whatsapp, Telegram, instagram X and others

**Comment by jaredhirsch** [comment]
Thanks for the suggestion. Side view is in maintenance mode and I'm not adding new features. That said, if you bring your suggestion to connect.mozilla.org, maybe your idea will get noticed by product folks, and possibly make its way into the feature set if the product folks ever decide to build a split view feature into the browser directly.
