### ISSUE TITLE
Cannot get a local profile (from the Firefox profiler) in the side view

### ISSUE THREAD

**Issue by calixteman** [mozilla/side-view#473]
STR:
 - start the Firefox profiler
 - stop it
 - a profile should open in a new tab
 - click on the side-view button

The profile can't be loaded: 
![image](https://github.com/user-attachments/assets/84bba7d2-947e-422e-83f5-30f2c8582512)

It'll be useful in order to be able to compare two profiles.
There's a workaround: upload the profile, but it'd be better to avoid that.

**Comment by julienw** [comment]
For more context, the profile glue maps a tab browser object with its profile value (see https://searchfox.org/mozilla-central/search?q=symbol:%23infoForBrowserMap&redirect=false). I suppose that the sideview creates a different tab browser than the original one. Therefore the glue can't find the profile data.
If we could be pingued with the old tabbrowser and the new tabbrowser, we could definitely change the map to account for that.

**Comment by jaredhirsch** [comment]
the side view is just a webextension, so it runs in a content window context with limited privileges. as far as I'm aware, the webextension sidebar window's visibility into tabs is limited to what's exposed by the [tabs API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs).

**Comment by jaredhirsch** [comment]
if you'd like to explore this further, note that you can attach the debugger to an addon window context, see https://extensionworkshop.com/documentation/develop/debugging/

**Comment by jaredhirsch** [comment]
Closing as I'm not sure there's anything more we can do here.
