### ISSUE TITLE
[New enhance] Make the 2 views consistent

### ISSUE THREAD

**Issue by AutogeneratedEngine** [mozilla/side-view#474]
Hello everyone, is there any option to hide the top bar in side view. I have a website deployed in 2 environments so I want to test at the same size, same resolution, each pixel needs to be compared but as you can see below it is pushed down and skewed. I would really appreciate if there was more of a feature to hide that red area. I also wish there would be more information like a url to determine what the side view is displaying
Thank you everyone

![image](https://github.com/user-attachments/assets/4b1c8d61-afea-4c6e-933b-33a7bb25fa84)

**Comment by jaredhirsch** [comment]
Hi, thanks for filing this bug. It might be possible to hide that top bar using a userChrome.css rule, you'd have to poke at it using the inspector pane of the browser toolbox.

Just a side note--pixel-by-pixel comparisons are brittle, but if you need to take this approach, maybe look into automating it using selenium webdriver, which can load URLs, resize the screen, and take screenshots.
