### ISSUE TITLE
Add QA testplan

### ISSUE THREAD

**Issue by pdehaan** [mozilla/side-view#53]
Via archived https://github.com/mozilla/tab-split/issues/11

> Once we have a functioning add-on to play with, we should write a QA testplan that we can use to verify releases.
>
> Initially, I'd want to make sure that devtools and fullscreen and Activity Stream and stuff like Min-Vid/Lockbox all work as expected with a split viewport.

/cc @SoftVision-PaulOiegas @Softvision-CristinaBadescu

**Comment by wresuolc** [comment]
thanks for filing this @pdehaan !

**Comment by pdehaan** [comment]
My pleasure.  My copy-pasta skills are strong... And speaking of, it looks like there may already be a test plan doc (which I should probably have noticed before since I was explicitly name checked):

Per @SoftVision-PaulOiegas's https://github.com/mozilla/tab-split/issues/11#issuecomment-364460404:

> _Yes, @Softvision-CristinaBadescu is actively testing what already landed but at a lower rate since we are swarmed for the moment with several other tasks. Right now we are still helping our old Engineering QA team while we also migrated to new tasks (shield studies especially) that we will be doing as the new Test Pilot QA team._
>
> _However, the first draft of the Test Plan for Tabs Split is already in review, but we could use a review form you if you can help us. [Here](https://docs.google.com/document/d/1D-wk5Yzr04RBW9RWAA3KQTecXl0aSBXTHrb1N9yDMrM/edit#heading=h.p8sqis9mpzyv) it is._
>
> _We also have the Test Cases created but we haven't imported them yet into Test Rail. Will let you know when this will happen._

**Comment by Softvision-CristinaBadescu** [comment]
[Here](https://docs.google.com/document/d/1D-wk5Yzr04RBW9RWAA3KQTecXl0aSBXTHrb1N9yDMrM/edit#heading=h.z6ne0og04bp5) is an updated version of the QA Test Plan based on the new sidebar approach.
I didn't change yet the experiment's name into "Side View" until this settels. 

We could also use a review from you @pdehaan , if you can please help us.
We'll start creating the new Test Cases also this week (the previous ones are kind of obsolete now) and we'll let you know when we will import them in Test Rail.

**Comment by pdehaan** [comment]
👍 This looks totally great!

We should probably add links to TestRail to the test plan once they get imported.

Not sure if we have a list of domains somewhere that we're checking if they work in the **Side View** or not. I didn't see any bugs or anything in the test plan saying that these top 10-20 sites from [Alexa top sites](https://www.alexa.com/topsites), not sure if there is a TestRail bug for it or if it's something we're manually testing, but it may be interesting since those could be the sites most likely to have CSP issues or frame breakers or any other potentially visible issues.

**Comment by pdehaan** [comment]
I also think we can probably just make a `./docs/qa-testplan.md` doc and redirect it to the https://docs.google.com/document/d/1D-wk5Yzr04RBW9RWAA3KQTecXl0aSBXTHrb1N9yDMrM/edit#heading=h.z6ne0og04bp5 Google Doc/TestRail and close this tracking issue.
