### ISSUE TITLE
Implement and verify metrics pings

### ISSUE THREAD

**Issue by johngruen** [mozilla/side-view#68]

**Comment by ianb** [comment]
Some notes / questions:

1. We don't know the sidebar width at the time we start opening a page, only when the sidebar is later opened. So it's hard to fill in cd1 at the "normal" location.
2. There doesn't seem to be a reasonable way to distinguish between the tab context menu and the page context menu.
3. Do we want a startup ping?
4. We don't have a keyboard shortcut
5. should showing the homepage be a load-url event?
6. We're missing a browserAction event
7. Are we cool not bucketing sidebar widths (pixels)?
8. Add an event for when we can't save something to recentTabs?
