### ISSUE TITLE
The sidebar's Homepage UI is wrongly displayed instead of the previously opened website, after the sidebar is switched or reopened

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#73]
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have the Tab Split sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to a website.
2. Click the tab from the "Current Tabs" section.
3. Change the sidebar to "Bookmarks".
4. Switch back to "Tab Split" and observe the displayed content.

[Expected result]:
- The previously opened website is displayed.

[Actual result]:
- The Tab Split's Homepage UI is displayed.

[Notes]:
- This behavior is already present for the "Bookmarks" and "History" sidebars.
- Here is a screen recording with this issue:
![tab split 2 - switch sidebar](https://user-images.githubusercontent.com/31244235/37213262-2d11de8e-23ba-11e8-8e9a-666a86566aae.gif)

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version of Tab Split (built on 3/16/2018) on Windows 10 x64, Mac 10.13.3 and Arch Linux. The last opened website in the sidebar will be displayed when the sidebar is switched back.

**Comment by Softvision-CristinaBadescu** [comment]
I'm going to reopen this issue since it is reproducible using Side View v0.2.0 on latest Nightly build 61.0a1 (2018-03-29), latest Firefox Release 59.0.2, on Windows 10 x64, Mac 10.13.3 and Ubuntu 14.04 x64.

Also, this issue is reproducible for websites loaded in the sidebar from the "Recent Tabs" section.

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for fixing this! The issue is no longer reproducible using Side View v0.2.0 (custom built on 2018-04-04), on latest Nightly build 61.0a1 (2018-04-04), on Windows 10 x64, Mac 10.13.3 and Ubuntu 14.04 x64.
