### ISSUE TITLE
The sidebar wrongly remains blank when the "YouTube" page is sent to it

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#82]
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have the Tab Split sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to https://www.youtube.com/.
2. Click the "Open current tab in sidebar" toolbar button and observe the behavior.

[Expected result]:
- The site is displayed in the sidebar.

[Actual result]:
- The header of the site appears for a brief moment and afterwards the sidebar is blank.

[Notes]:
- This issue is also reproducible for the "Open in sidebar" option from the tab strip context menu, the "Open link in sidebar" context menu option or if you click the page from the "Current Tabs" sidebar's section.
- I've also encountered the behavior regarding the blank page on the "https://mail.google.com" page.
- This issue is not reproducible if you select "Request desktop site" checkbox, on Arch Linux 4.12 and Mac 10.12.6. But on Windows 10 x64 the page's left margin is not entirely visible.
- Here is a screen recording with this issue:
![split 2 - youtube blank](https://user-images.githubusercontent.com/31244235/37341757-39767a90-26cb-11e8-8408-7e70b22218aa.gif)

**Comment by ianb** [comment]
I'm not seeing quite this myself, though it does seem like the YouTube homepage (not individual video pages) seems to want to send me the desktop page (though if I go to https://m.youtube.com/ then it all works fine, except for terribly low-resolution preview images).

We might consider special-casing this one site, and rewriting the homepage URL to `m.youtube.com`.

YouTube appears to have some cookies that make your mobile selection sticky. I can't figure out how to get back to the normal YouTube site now :( If I manually remove the `PREF` cookie then it lets me get back to the normal front page.

**Comment by fzzzy** [comment]
This seems like it was fixed by switching to the 0.3 panel, but the desktop site is currently being accessed. There's a bug for that: https://github.com/mozilla/side-view/issues/154

**Comment by fzzzy** [comment]
Nope, once the code that sends requests as mobile was fixed for the 0.3 panel version, this bug came back.

**Comment by ianb** [comment]
Fixed in 23f17ca0587f7d5b1d2f8a10354888766ec09e3a

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Side View v0.3.2, on latest Nightly build 61.0a1 (2018-04-25), on Windows 10 x64, Mac 10.13.4 and Ubuntu 14.04 x64. The YouTube is opened by default to its desktop site version.
