### ISSUE TITLE
Certain about:* pages are not loaded when they are sent to the sidebar

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#83]
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have the Tab Split sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the "about:addons" page.
2. Click the "Open current tab in sidebar" toolbar button and observe the behavior.

[Expected result]:
- The homepage UI remains displayed.

[Actual result]:
- The sidebar becomes blank.

[Notes]:
- The issue is reproducible with most about pages (see about:about) except for about:home, about:license and about:logo.
- Here is a screen recording with this issue:
![tab split 2 - blank sidebar](https://user-images.githubusercontent.com/31244235/37354794-2514a23c-26eb-11e8-9753-50326ba3654f.gif)

**Comment by johngruen** [comment]
This is no longer reproducable

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Side View 0.3.2 (custom built on 2018-04-18), on latest Nightly build 61.0a1 (Build ID: 20180418112600), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12. Only the "about:credits" page (which redirect you to https://www.mozilla.org/credits/) can be opened in the sidebar; the other about:pages cannot be sent to it.

**Comment by stapuft** [comment]
this is now reproducible again, it affects all entries from the bookmarks bar, as well as history entries,in the library menu.
