### ISSUE TITLE
Imgur pages never finish loading when they are sent to the sidebar

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/side-view#88]
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have the Tab Split sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to https://imgur.com/.
2. Right click a link or image and choose the "Open link in sidebar" option.
3. Observe the behavior.

[Expected result]:
- The link is loaded in the sidebar.

[Actual result]:
- The link remains stuck in the website's loading animation.

[Notes]:
- The issue is also reproducible if the tab is sent to sidebar or the "Open current tab in sidebar" toolbar button is clicked.
- This issue is not reproducible if the desktop site is requested.
- Here is a screen recording with this issue:
![imgur never finishes loading](https://user-images.githubusercontent.com/18304511/37524599-f59f8bb2-2932-11e8-82f5-d896386613d2.gif)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is also reproducible on https://www.reddit.com/, https://www.pinterest.com/ and https://twitter.com/, using latest Side View build v0.2.0, using latest Nightly build 61.0a1 (2018-04-01), on Windows 10 x64, Mac 10.13.3 and Ubuntu 14.04 x64.

**Comment by ianb** [comment]
I reconfirmed with the new sidebar (that has no iframe) and imgur still isn't loading, nothing interesting in the console.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Side View v0.3.2, on latest Nightly build 61.0a1 (2018-04-25), on Windows 10 x64, Mac 10.13.4 and Ubuntu 14.04 x64. The websites are opened by default to their desktop version.
