### ISSUE TITLE
The feedback button is not stuck to the bottom of the sidebar

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/side-view#89]
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have the Tab Split sidebar open.
- Have over 20 tabs opened.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Scroll down to the bottom of the sidebar and observe the "Feedback" button's position.

[Expected result]:
- The "Feedback" button is at the bottom of the sidebar.

[Actual result]:
- The "Feedback" button is displayed over the tabs around the middle of the sidebar.

[Notes]:
- Here is a screen recording with this issue:
![feedback button is not stuck at the bottom of the sidebar](https://user-images.githubusercontent.com/18304511/37526847-1f3e885a-2939-11e8-96f6-e65238bb6d05.gif)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Side View v0.2.0 (custom built on 2018-04-05), on latest Nightly build 61.0a1 (2018-04-04), on Windows 10 x64, Mac 10.12.6 and Ubuntu 14.0x x64.
