### ISSUE TITLE
Homepage UI flashes in the Tab Split sidebar when you switch back to it

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/side-view#90]
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have the Tab Split sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and send a link to the sidebar.
2. Switch to a different sidebar (Bookmarks, History, etc).  
3. Switch back to the Tab Split sidebar and observe the behavior.

[Expected result]:
- The last visited website is displayed in the sidebar.

[Actual result]:
- The Tab Split homepage UI is quickly displayed in the sidebar before loading the website.

[Notes]:
- Here is a screen recording with this issue:
![homepage ui and loading pages flash when you switch back to the sidebar](https://user-images.githubusercontent.com/18304511/37525426-7d3cf2ba-2935-11e8-823b-a8599846742a.gif)

**Comment by ianb** [comment]
We'll try to replace the homepage here with a blank page
