### ISSUE TITLE
[Enhancement] Add an animation to the loading page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/side-view#91]
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have the Tab Split sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Send a link or tab to the sidebar and observe the loading page.

[Expected result]:
- A loading animation is displayed while the page is loaded.

[Actual result]:
- There is no animation.

[Notes]:
- If you have poor internet speed, this would improve user experience while waiting for the page to load.
- Here is a screen shot of the issue:
<img width="1280" alt="screen shot 2018-03-16 at 4 19 24 pm" src="https://user-images.githubusercontent.com/18304511/37525957-e2c368b6-2936-11e8-8148-65146ad9b141.png">

**Comment by johngruen** [comment]
@ianb @fzzzy can u guys figure out how to do a blank page or like make it background: lime

**Comment by johngruen** [comment]
Assigning this to @ianb to handle making a loading page

**Comment by ianb** [comment]
I tried this, and it didn't work: the page still was white during rendering. So I'm assuming that the new page replaces the old page right away, but the blank white space is just what's put into place while it's rendering.

**Comment by johngruen** [comment]
maybe we should file an upstream bug? 🤷‍♂️

**Comment by Softvision-CristinaBadescu** [comment]
Sure thing. I've filed it here: bug [1460246](https://bugzilla.mozilla.org/show_bug.cgi?id=1460246).

**Comment by ExE-Boss** [comment]
See #327
