### ISSUE TITLE
There is a noticeable delay until tabs are removed from the sidebar when they are closed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/side-view#92]
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have the Tab Split sidebar open.
- Have at least 4 tabs opened.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to the sidebar's homepage.
3. Close a tab and observe the sidebar.

[Expected result]:
- The tab is instantly removed from the list.

[Actual result]:
- There is a bit of delay until the tab is removed.

[Notes]:
- Here is a screen recording of the issue:
![noticeable delay untile tabs are closed](https://user-images.githubusercontent.com/18304511/37526375-d4181c52-2937-11e8-8bab-5eccc2e8938d.gif)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer applicable.
