### ISSUE TITLE
Consider implementing zoom

### ISSUE THREAD

**Issue by wresuolc** [mozilla/side-view#93]
With a 4k monitor, pretty much every website is hard for me to read now.  If I haven't been to a website, ctrl+scrollwheel is pretty much just a habit for me.  Maybe we should support zooming in the sidebar?

**Comment by Softvision-CristinaBadescu** [comment]
Currently, the sidebar can be zoomed on Windows OSes but not on Linux or Mac OSes. There is a known issue encountered for another experiment, logged in Bugzilla, #[1382659](https://bugzilla.mozilla.org/show_bug.cgi?id=1382659).

So, if we consider keeping this behavior, we should also think about having the option to restore the sidebar content to the default zoom level.

**Comment by clouserw** [comment]
ctrl-scrollwheel is working now!
