### ISSUE TITLE
 Confirm URL origin when rewriting X-Frame-Options/etc

### ISSUE THREAD

**Issue by ianb** [mozilla/side-view#97]
We *probably* know the URL that is being loaded in the iframe, and in the webRequest overrides we could confirm that we only rewrite requests that we are expecting. (Or we can use that same request to update the URL we display...?)

**Comment by ianb** [comment]
I think we need to figure out #98 and #114 before we will know if we can do this.

**Comment by fzzzy** [comment]
We're not going to be rewriting x-frame-options any more.
